## EDUNET FOUNDATION - Self-Practice Exercise Notebook

### LAB 8 - Implementing Numpy Concepts in Python

Problem 1: Write a NumPy program to test whether none of the elements of a given array are zero.

In [4]:
import numpy as np
a = np.array(list(map(int,input().split())))
print(np.all(a != 0))
    

0 1 2 
False


Problem 2: Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 

In [7]:
np.array([0]*10+[1]*10+[5]*20)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

Problem 3: Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [8]:
a = np.random.randn(15)
print(a)

[-1.32331409 -0.56193595  0.68008573  1.99899885  0.18613847 -0.10847903
 -0.90244717 -0.42515232  0.51931212  0.58974693  0.67080263 -0.08496469
  1.25093176  0.8454227  -0.52625292]


Problem 4: Write a NumPy program to create a two-dimensional array with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7).

In [9]:
arr = np.random.normal(200, 7, (8, 5))
print(arr)

[[192.35026348 202.26097954 208.65469828 189.32697335 203.09513304]
 [202.08796589 195.05759237 204.76551878 212.30392026 198.95329816]
 [190.08870761 194.46244345 202.4352901  208.7339693  192.39983164]
 [202.3963613  206.93375529 204.5800057  186.73084849 198.52128365]
 [204.72953335 205.61646237 213.10885298 195.8942631  207.07044337]
 [198.95494636 196.12964445 206.65799719 203.54922804 213.60863796]
 [190.97012826 196.27267031 192.84019552 195.22085249 201.03251809]
 [207.92598347 189.80623435 208.91934424 202.65596176 202.53342779]]


Problem 5: Write a NumPy program to create a 4x4 array. Create an array from said array by swapping first and last, second and third columns.

In [12]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
a[0],a[3] = a[3],a[0]
a[1],a[2] = a[2],a[1]
a

array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Problem 6: Write a NumPy program to swap rows and columns of a given array in reverse order.

In [16]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
a = a[::-1,::-1]
a

array([[16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

Problem 7: Write a NumPy program to multiply two given arrays of the same size element-by-element.

In [17]:
a = np.array([1,2,3,4])
b = np.array([3,2,1,5])
a*b

array([ 3,  4,  3, 20])

Problem 8: Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [19]:
np.arange(2, 11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

Problem 9: Write a NumPy program to create a 3x3x3 array with random values.
Expected Output:

[[[ 0.48941799 0.58722213 0.43453926]
[ 0.94497547 0.81081709 0.1510409 ]
[ 0.66657127 0.29494755 0.48047144]]
[[ 0.02287253 0.95232614 0.32264936]
[ 0.67009741 0.25458304 0.16290913]
[ 0.15520198 0.86826529 0.9679322 ]]
[[ 0.13503103 0.02042211 0.24683897]
[ 0.97852158 0.22374748 0.10798856]
[ 0.62032646 0.5893892 0.16958144]]]

In [23]:
arr = np.random.rand(3, 3, 3)

print(arr)

[[[0.40029801 0.36313682 0.0224652 ]
  [0.78987402 0.99529936 0.64315452]
  [0.0913036  0.76181513 0.76141953]]

 [[0.29668106 0.09283095 0.70603639]
  [0.42145386 0.95292587 0.93053855]
  [0.47366699 0.32316424 0.39656727]]

 [[0.51952926 0.19966152 0.55957081]
  [0.15557692 0.22151773 0.82809399]
  [0.0646046  0.29811728 0.45745961]]]


Problem 10: Write a Python program to find the maximum and minimum value of a given flattened array.

In [24]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print("min:",np.min(a))
print("max:",np.max(a))

min: 1
max: 6


Problem 11: Write a NumPy program to add, subtract, multiply, divide arguments element-wise.     
Expected Output:
Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25

In [30]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([12, 22, 13])
add_result = arr1 + arr2
subtract_result = arr1 - arr2
multiply_result = arr1 * arr2
divide_result = arr1 / arr2

print("Add:", add_result)
print("Subtract:", subtract_result)
print("Multiply:", multiply_result)
print("Divide:", divide_result)

Add: [13 24 16]
Subtract: [-11 -20 -10]
Multiply: [12 44 39]
Divide: [0.08333333 0.09090909 0.23076923]


Problem 12: Write a NumPy program to get the powers of an array values element-wise.
Note: First array elements raised to powers from second array
Expected Output:
Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[ 0 1 8 27 64 125 216]

In [32]:
c = np.array([0,1,2,3,4,5,6])
c**2

array([ 0,  1,  4,  9, 16, 25, 36])

Problem 13: Create a Python project to guess a number that has randomly selected.

In [34]:
import random as rand
x = rand.randint(1, 100)
i= 0
r = 0
while(i < 3):
    d = int(input("Guess Number:"))
    if(x == d):
        print(f"You Win With {(3-i)*10} Score")
        r= 1
        break
    elif(x<d):
        print("Guess is High")
    elif(x>d):
        print("Guess is Low")
    i+=1
if(r == 0):
    print("You loose")

Guess Number:12
Guess is Low
Guess Number:50
Guess is Low
Guess Number:100
Guess is High
You loose


Problem 14: Write a NumPy program to create a 2D array with 1 on the border and 0 inside.        
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

In [43]:
n = int(input())
d = np.zeros((n,n))
d[0,:] = 1
d[n-1,:] = 1
d[:,0] = 1
d[:,n-1] = 1
d

6


array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

Problem 15: Write a NumPy program to append values to the end of an array.                      
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [47]:
d = np.array(list(map(int,input().split())))
np.append(d,np.array(list(map(int,input().split()))))


1 2 3 4
8 7 6


array([1, 2, 3, 4, 8, 7, 6])